[COURSE HEADER]
VERSION = 2
UNITS = ENGLISH
DESCRIPTION = Creator: Matthias B
FILE NAME = 4wkFTPBoosterW4D5Endurancenr5_D6=Restday_
MINUTES PERCENT
[END COURSE HEADER]
[COURSE DATA]
0.00	67
60.00	67
[END COURSE DATA]
